#!/bin/bash

SEED=$(awk -v min=0 -v max=1 'BEGIN{srand(); print min+rand()*int(1000*(max-min)+1)/1000}')
WIDTH=1080

mkdir ./generated/seed-$SEED &> /dev/null

./planet/planet -s $SEED -l 0.0 -po -E -O10 -c -C ./planet/default.col -w $WIDTH -h $WIDTH -o ./generated/seed-$SEED/contour-0.bmp 
# ./planet/planet -s $SEED -l 0.0 -po -c -C ./planet/default.col -z -Z ./planet/default.bio -w $WIDTH -h $WIDTH -o ./generated/seed-$SEED/biome-0.bmp


./planet/planet -s $SEED -l 90.0 -po -E -O10 -c -C ./planet/default.col -w $WIDTH -h $WIDTH -o ./generated/seed-$SEED/contour-90.bmp 
# ./planet/planet -s $SEED -l 90.0 -po -c -C ./planet/default.col -z -Z ./planet/default.bio -w $WIDTH -h $WIDTH -o ./generated/seed-$SEED/biome-90.bmp

./planet/planet -s $SEED -l 180.0 -po -E -O10 -c -C ./planet/default.col -w $WIDTH -h $WIDTH -o ./generated/seed-$SEED/contour-180.bmp 
# ./planet/planet -s $SEED -l 180.0 -po -c -C ./planet/default.col -z -Z ./planet/default.bio -w $WIDTH -h $WIDTH -o ./generated/seed-$SEED/biome-180.bmp

./planet/planet -s $SEED -l 270.0 -po -E -O10 -c -C ./planet/default.col -w $WIDTH -h $WIDTH -o ./generated/seed-$SEED/contour-270.bmp 
# ./planet/planet -s $SEED -l 270.0 -po -c -C ./planet/default.col -z -Z ./planet/default.bio -w $WIDTH -h $WIDTH -o ./generated/seed-$SEED/biome-270.bmp

./planet/planet -s $SEED -L "-90.0" -po -E -O10 -c -C ./planet/default.col -w $WIDTH -h $WIDTH -o ./generated/seed-$SEED/contour-S.bmp 
# ./planet/planet -s $SEED -L "-90.0" -po -c -C ./planet/default.col -z -Z ./planet/default.bio -w $WIDTH -h $WIDTH -o ./generated/seed-$SEED/biome-S.bmp

./planet/planet -s $SEED -L 90.0 -po -E -O10 -c -C ./planet/default.col -w $WIDTH -h $WIDTH -o ./generated/seed-$SEED/contour-N.bmp 
# ./planet/planet -s $SEED -L 90.0 -po -c -C ./planet/default.col -z -Z ./planet/default.bio -w $WIDTH -h $WIDTH -o ./generated/seed-$SEED/biome-N.bmp